-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "stars" bigint NOT NULL, "nickname" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "user_nickname" to table: "users"
CREATE UNIQUE INDEX "user_nickname" ON "users" ("nickname");
