// Code generated by ent, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStars holds the string denoting the stars field in the database.
	FieldStars = "stars"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldStars,
	FieldNickname,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StarsValidator is a validator for the "Stars" field. It is called by the builders before save.
	StarsValidator func(int) error
)
